name: Yes That Kevin Hunt
favicon: null
layout_spectrum: 0.1798
typography_spectrum: 0.75055
title: Yes That Kevin Hunt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f6f4'
    - '#d0d0d0'
    - '#8ea7c1'
    - '#332323'
    - '#787c8d'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
