name: YesThatKevinHunt
favicon: null
layout_spectrum: 0.84487
typography_spectrum: 0.75055
title: Yes That Kevin Hunt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f7f4'
    - '#d0d0d0'
    - '#2e1e1e'
    - '#67708f'
    - '#6e3a2d'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
