name: YesThatKevinHunt
favicon: null
layout_spectrum: 0.9125440225470811
typography_spectrum: 0.9793593373615295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f7f4'
    - '#d0d0d0'
    - '#2e1e1e'
    - '#67708f'
    - '#6e3a2d'
  brandStrength: 0.375
  lightness: 0.3896709540858865
  saturation: 0.3263352147769183
  rhythmicContrast: 0.03556736069731414
purpose: []
